// #define ONE buttons[0]
// #define TWO buttons[1]
// #define THREE buttons[2]
// #define FOUR buttons[3]
// #define FIVE buttons[4]
// #define SIX buttons[5]
// #define SEVEN buttons[6]
// #define EIGHT buttons[7]
// #define AXES_UD axes[5]
// #define AXES_LR axes[4]
// #define STICK_L_LR axes[0]
// #define STICK_L_UD axes[1]
// #define STICK_R_LR axes[3]

#define A buttons[0]
#define B buttons[1]
#define X buttons[2]
#define Y buttons[3]
#define LB buttons[4]
#define RB buttons[5]
#define WINDOWS buttons[6]
#define LIST buttons[7]
#define AXES_UD axes[7]
#define AXES_LR axes[6]
#define STICK_L_LR axes[0]
#define STICK_L_UD axes[1]
#define STICK_R_LR axes[3]

